"""Create table clients

Revision ID: dffcfd173d82
Revises: 7a55347b045f
Create Date: 2018-04-29 14:13:18.772018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dffcfd173d82'
down_revision = '7a55347b045f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'clients',
        sa.Column('id', sa.String(length=100), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('secret', sa.String(length=50), nullable=False),
        sa.Column('_is_confidential', sa.Boolean(), nullable=False),
        sa.Column('_allowed_grant_types', sa.Text(), nullable=False),
        sa.Column('_redirect_uris', sa.Text(), nullable=True),
        sa.Column('_default_scopes', sa.Text(), nullable=True),
        sa.Column('deleted', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_clients_secret'), 'clients', ['secret'], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_secret'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
